// <auto-generated />
using System;
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531064702_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MVC.Models.Entity.CattleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CattleType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f571f132-1320-40dc-96a0-85b326790ca0"),
                            Is_active = true,
                            Name = "Type1",
                            Note = "Note for Type1"
                        });
                });

            modelBuilder.Entity("MVC.Models.Entity.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Buy_Price")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Female_Breeder")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Investor_Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Male_Breeder")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sell_Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Treament_Price")
                        .HasColumnType("int");

                    b.Property<Guid>("Type_Id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Investor_Id");

                    b.HasIndex("Type_Id");

                    b.ToTable("Farm");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f67877d-28c5-4a89-8083-609976b90509"),
                            Buy_Price = 1000,
                            Code = "FARM001",
                            Female_Breeder = new Guid("30f5ebbb-5afb-4ac6-969b-972acc5a2dee"),
                            Investor_Id = new Guid("706304b7-8b75-49f9-8bb7-c51d421cc08a"),
                            Male_Breeder = new Guid("10cb5f9b-6ca0-4fc1-a081-bdca6edf4e5d"),
                            Sell_Price = 1500,
                            Status = 1,
                            Treament_Price = 200,
                            Type_Id = new Guid("f571f132-1320-40dc-96a0-85b326790ca0")
                        });
                });

            modelBuilder.Entity("MVC.Models.Entity.FarmExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Farm_Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Img1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Img2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Img3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Img4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Img5")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Farm_Id");

                    b.ToTable("FarmExpense");
                });

            modelBuilder.Entity("MVC.Models.Entity.FarmExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FarmExpenseCategory");
                });

            modelBuilder.Entity("MVC.Models.Entity.FarmImg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Category_Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Farm_Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Img1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Img2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Img3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("Farm_Id");

                    b.ToTable("FarmImg");
                });

            modelBuilder.Entity("MVC.Models.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("706304b7-8b75-49f9-8bb7-c51d421cc08a"),
                            Email = "john.doe@example.com",
                            Is_active = true,
                            Name = "John Doe",
                            Password = "password123",
                            Phone = "1234567890",
                            Role = "investor"
                        });
                });

            modelBuilder.Entity("MVC.Models.Entity.Farm", b =>
                {
                    b.HasOne("MVC.Models.Entity.User", "Investor")
                        .WithMany()
                        .HasForeignKey("Investor_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC.Models.Entity.CattleType", "Type")
                        .WithMany()
                        .HasForeignKey("Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MVC.Models.Entity.FarmExpense", b =>
                {
                    b.HasOne("MVC.Models.Entity.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("Farm_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("MVC.Models.Entity.FarmImg", b =>
                {
                    b.HasOne("MVC.Models.Entity.FarmExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC.Models.Entity.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("Farm_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Farm");
                });
#pragma warning restore 612, 618
        }
    }
}
